server:
  port: 20100
  contextPath: /
spring:
  application:
    name: zuul-service
  zipkin:
    base-url: http://localhost:9411
    service:
      name: ${spring.application.name}
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:20080/eureka/
    registry-fetch-interval-seconds: 3
token:
  header: access_token
jwt: 
  expireTime: 180000
  pubKeyPath: C:\springcloud_service_modules\keyfile\pubKey.key  
#  pubKeyPath: D:\springcloud\keyfile\pubKey.key
zuul:
#  ignored-services: "*"
  ignored-url:
    login: /auth/login
    logout: /auth/logout
  prefix: /api
  routes:
    auth:
      path: /auth/**
      sensitiveHeaders: Cookie,Set-Cookie,Authorization
      serviceId: auth-service
    ugwater:
      path: /ugwater/**
      sensitiveHeaders: Cookie,Set-Cookie,Authorization
      serviceId: ugwater-service
management:
  security:
    enabled: false
ribbon:  
  ReadTimeout: 10000
  ConnectTimeout: 10000