server:
  port: 38254
  context-path: /term
spring:
  redis:
    host: 172.16.22.249
    port: 6379
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: 5
#  rabbitmq:
#    host: 172.16.8.60
#    port: 30601
#    username: admin
#    password: 123
#    virtualHost: /
  datasource: 
    url: jdbc:mysql://172.16.22.249:3316/irtu_itss?autoReconnect=true&amp;useUnicode=true&amp;characterEncoding=UTF-8
    username: root
    password: sa
    driver-class-name: com.mysql.jdbc.Driver
    
  application:
    name: term-service
#  zipkin:
#    base-url: http://localhost:9411
#    service:
#      name: ${spring.application.name}
#  jpa:
#    generate-ddl: true
#    hibernate:
#      ddl-auto: update
#    show-sql: true

sys:
  platName: 10004
  fep-itss-pattern: fep_itss
  fep-name-itss: fep_itss_comm
  fep-name-yjgb: rtu_hcs_yjgb
#  message:
#    exchange: amq.topic
#    queue: fep_to_${sys.platName}_queue
#    topic: fep.${sys.platName}.#
  mqtt:
    url: tcp://172.16.8.60
    port: 30600
    clientId: platform${sys.platName}
    username: admin
    password: 123
    qos: 1
    completionTimeout: 5000
    subTopic: fep/${sys.platName}/#
    pubTopicPrefix: plat/${sys.platName}/
  upgradepath:
    main: D:/upgrade/
    
logging:
  level:
    org: INFO

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://172.16.22.194:20080/eureka/
    registry-fetch-interval-seconds: 30000

mybatis-plus:
  mapper-locations: classpath:com/hongdian/plat/term/mapper/xml/*.xml
  typeAliasesPackage: com.hongdian.plat.term.entity
  typeHandlersPackage: com.ithings.xw.mybatis.handler
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 0
    logic-not-delete-value: 1
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    #自定义填充策略接口实现
    #meta-object-handler: com.ithings.iam.xxx
    #自定义SQL注入器
    #sql-injector: com.ithings.iam.xxx
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    #配置JdbcTypeForNull, oracle数据库必须配置
#    jdbc-type-for-null: 'null'